version: 2
name: Maintain dependencies for GitHub Actions

updates:
    # Maintain dependencies for GitHub Actions
    - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: "daily"
