[tool.commitizen]
name = "cz_conventional_commits"
version = "1.2.1"
tag_format = "$major.$minor.$patch$prerelease"
version_files = [
    "info.json",
    "package.json",
    "package-lock.json",
    "Dockerfile"
    ]
