[tool.commitizen]
name = "cz_conventional_commits"
version = "1.3.14"
tag_format = "$major.$minor.$patch$prerelease"
version_files = [
    "info.json:version",
    "package.json:version",
    "Dockerfile:VERSION"
    ]
