import { UserModel } from '../models/v1/User';
import { WorkspaceModel } from '../models/v1/Workspace';
import { connection } from './mongoose';

const ModelUser = UserModel();
const ModelWorkspace = WorkspaceModel();

const initUser = async (user) => {
  try {
    const request = {
      email: user.email,
    };
    const userFound = await ModelUser.findOne(request);
    if (!userFound) {
      console.error('user not in db', user.email);
      return await new ModelUser(user).save();
    }
    console.error('user already in db', user.email);
    return userFound;
  } catch (err) {
    console.error('user error', user.email);
    return null;
  }
};

const initWorkspace = async (workspace) => {
  try {
    const request = {
      _id: workspace._id,
    };
    const wpFound = await ModelWorkspace.findOne(request);
    if (!wpFound) {
      console.error('wp not in db', workspace.name);
      return await new ModelWorkspace(workspace).save();
    }
    console.error('wp already in db', workspace.name);
    return wpFound;
  } catch (err) {
    console.error('wp error', workspace.name);
    return null;
  }
};

export const cleanDb = async (name: string = null) => {
  if (name) {
    const db = connection.useDb(name);
    await db.dropDatabase();
    // eslint-disable-next-line no-console
    console.log(`${name} database dropped.`);
  } else {
    await connection.db.dropDatabase();
    // eslint-disable-next-line no-console
    console.log(`${connection.db.databaseName} database dropped.`);
  }
};

export const seedDb = async () => {
  if (process.env.NODE_ENV !== 'production') {
    await initWorkspace({
      _id: '5cc22e6efc3b6947d92d37f2',
      logo: {
        url: '.../../../assets/logo/nexity.png',
        name: 'testUpload',
      },
      name: 'admin',
      bobVoice: true,
      menu: [
        {
          title: 'Data Story',
          icon: 'eye',
          sectionId: 1,
        },
        {
          title: 'Task Manager',
          icon: 'tasks',
          sectionId: 2,
        },
        {
          title: 'Documentation',
          icon: 'book',
          sectionId: 3,
        },
        {
          title: 'Data factory',
          icon: 'plug',
          sectionId: 4,
        },
        {
          title: 'AI training',
          icon: 'brain',
          sectionId: 5,
        },
        {
          title: 'File Manager',
          icon: 'cabinet-filing',
          sectionId: 6,
        },
        {
          title: 'CashStory Admin',
          icon: 'chart-network',
          sectionId: 7,
        },
        {
          title: 'Workspaces',
          icon: 'globe',
          sectionId: 8,
        },
        {
          title: 'Users',
          icon: 'users',
          sectionId: 9,
        },
      ],
      sections: [
        {
          box: [
            {
              hideElements: [],
              _id: '5da87b33502d6c7d873aa7d0',
              name: 'Accounting firms',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              cors: 'false',
              urlBg: 'https://api-mdm-is.toucantoco.com/cashstory-acounting/assets/bg-1?decache=1556538973514&thum',
              url: 'https://cashstory.toucantoco.com/',
              autoExpand: false,
              position: 0,
              authMethod: 'toucan_cloud',
              login: {
                username: 'demo@cashstory.com',
                password: 'cashstory',
              },
            },
            {
              hideElements: [],
              _id: '5da87b33502d6cdbb93aa7cf',
              name: 'Finance Department',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              cors: 'false',
              urlBg: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80',
              url: 'http://akveo.com/ngx-admin/pages/layout/stepper',
              autoExpand: false,
              position: 1,
              login: {
                username: 'bob@cashstory.com',
                password: 'cspw007!',
              },
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c634b3aa7ce',
              name: 'Financial Institutions',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              cors: 'false',
              urlBg: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80',
              url: 'http://akveo.com/ngx-admin/pages/layout/stepper',
              autoExpand: false,
              position: 2,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c276a3aa7cd',
              authMethod: 'toucan',
              name: 'Power BI',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              cors: 'false',
              urlBg: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80',
              url: 'https://app.powerbi.com/groups/me/apps',
              autoExpand: false,
              position: 3,
              login: {
                username: 'jeremy.ravenel@cashstory.com',
                password: 'ESCesi0512.',
              },
            },
          ],
          id: 1,
          title: 'Stories',
          description: 'Follow your financial & extra-financial performance',
        },
        {
          box: [
            {
              hideElements: [
                'header-main-bar',
                'header-quick-access',
              ],
              _id: '5da87b33502d6cf74c3aa7cc',
              authMethod: 'wekan',
              name: 'Activity Manager',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://cdn-images-1.medium.com/max/1500/1*_POsBMENIdbKy873d2zATg.png',
              url: 'https://task.cashstory.com/',
              autoExpand: true,
              position: 0,
              login: {
                username: 'bob@cashstory.com',
                password: 'vog21d3tg9gs7xy8xseba',
              },
            },
          ],
          id: 2,
          title: 'Bob\'s tasks',
          description: 'Manage AI tasks, with our augmented to-do list',
        },
        {
          box: [
            {
              hideElements: [],
              _id: '5da87b33502d6ce4963aa7cb',
              name: 'Reference documentation',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://access42.net/IMG/arton479.jpg?1520440320',
              url: 'https://docs.google.com/document/d/1U8CDv5O1xORf2QWYtDOKb8i1WJ3reXeM2SlkG1b6iis/edit',
              autoExpand: false,
              position: 0,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6ca2a53aa7ca',
              name: 'Sharepoint',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://www.cnetfrance.fr/i/edit/2018/10/microsoft-1-big.jpg',
              url: 'https://cashstory-my.sharepoint.com/:w:/g/personal/jeremy_cashstory_onmicrosoft_com/ER91yVGXOzNDm7y3U4vvkqsBDpgXLLlqSqRAPSHXlpfh-w?e=VRoblH',
              autoExpand: false,
              position: 1,
            },
            {
              hideElements: [],
              _id: '5dd2b4c892b583a08cd697d3',
              name: 'Mattermost',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://images.unsplash.com/photo-1523668363792-50e1543e2cd3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80?raw=true',
              url: 'https://chat.cashstory.com',
              autoExpand: false,
              position: 2,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c29463aa7c9',
              name: 'Datafactory doc',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://images.unsplash.com/photo-1523668363792-50e1543e2cd3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80?raw=true',
              url: 'https://docs.google.com/document/d/1oQ8aY2QPR0VaZSDWq_XD9K1SIf7HGfX8vTqIKkMjVF4/edit',
              autoExpand: false,
              position: 3,
            },
          ],
          id: 3,
          title: 'Docs',
          description: 'Read the docs',
        },
        {
          box: [
            {
              hideElements: [],
              _id: '5da87b33502d6c0ba33aa7c8',
              name: 'Quick Books',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/FGJNTFTRQYmupi8sf/quickbooks.png?token=eyJhdXRoVG9rZW4iOiJ2U1VjZUdXVFNBMzl4X2JPclRlYnlBQ0ZzYVl5SmsyOFFoUk1YbWlSQUR2In0%3D',
              url: 'https://quickbooks.intuit.com/sign-in-offer/',
              autoExpand: false,
              position: 0,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c9b183aa7c7',
              name: 'Expensia',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/H6jEMmKLqJ4mYZ84s/expensya.png?token=eyJhdXRoVG9rZW4iOiJ2U1VjZUdXVFNBMzl4X2JPclRlYnlBQ0ZzYVl5SmsyOFFoUk1YbWlSQUR2In0%3D',
              url: 'https://www.expensya.com/Portal/#/Login?lang=en',
              autoExpand: false,
              position: 1,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c12323aa7c6',
              name: 'Jupyter Hub',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/6mKDNwTa7mAsozaNK/jupyterhub.png?token=eyJhdXRoVG9rZW4iOiJjOGxZUmlJWm5lb3NyUE1DRGtWMzhmM3lrTE9neUM4ZzdqUnR5d2VMZmJLIn0%3D',
              url: 'https://datascience.cashstory.com/hub/login?next=',
              autoExpand: false,
              position: 2,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c06373aa7c5',
              name: 'Postman',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/QeaS8jiDhFobz7ZJF/postman.png?token=eyJhdXRoVG9rZW4iOiJ2U1VjZUdXVFNBMzl4X2JPclRlYnlBQ0ZzYVl5SmsyOFFoUk1YbWlSQUR2In0%3D',
              url: 'https://identity.getpostman.com/login?continue=https%3A%2F%2Fapp.getpostman.com%2F%3F',
              autoExpand: false,
              position: 3,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c39c73aa7c4',
              name: 'Mongo DB',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/eQvp8rytMnbjg592h/mongodb.png?token=eyJhdXRoVG9rZW4iOiJ2U1VjZUdXVFNBMzl4X2JPclRlYnlBQ0ZzYVl5SmsyOFFoUk1YbWlSQUR2In0%3D',
              url: 'https://cloud.mongodb.com/user#/atlas/login',
              autoExpand: false,
              position: 4,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6ce61c3aa7c3',
              name: 'Tableau',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/mjCCKtvKGXvucuH7j/tableau.png?token=eyJhdXRoVG9rZW4iOiJ2U1VjZUdXVFNBMzl4X2JPclRlYnlBQ0ZzYVl5SmsyOFFoUk1YbWlSQUR2In0%3D',
              url: 'https://sso.online.tableau.com/public/idp/SSO',
              autoExpand: false,
              position: 5,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6cafae3aa7c2',
              name: 'SAP',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/o8b7jN6W8HDF7TJwp/sap.png?token=eyJhdXRoVG9rZW4iOiJjOGxZUmlJWm5lb3NyUE1DRGtWMzhmM3lrTE9neUM4ZzdqUnR5d2VMZmJLIn0%3D',
              url: 'https://accounts.sap.com/saml2/idp/sso/accounts.sap.com',
              autoExpand: false,
              position: 6,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c31803aa7c1',
              name: 'Sales force',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/xZoQG3oDx5euyaksr/salesforce.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://login.salesforce.com/?locale=eu',
              autoExpand: false,
              position: 7,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c7d3a3aa7c0',
              name: 'Hubspot',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/P4npAXyFeXDJNsFcG/hubspot.png?token=eyJhdXRoVG9rZW4iOiJ2U1VjZUdXVFNBMzl4X2JPclRlYnlBQ0ZzYVl5SmsyOFFoUk1YbWlSQUR2In0%3D',
              url: 'https://app.hubspot.com/login',
              autoExpand: false,
              position: 8,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c22323aa7bf',
              name: 'Qlik',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/f9J2drM32F2eiJ5uA/qlik.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://qlikid.qlik.com/signin',
              autoExpand: false,
              position: 9,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c21f03aa7be',
              name: 'Power BI',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/jB5DPWuJWjfFTv7v3/powerbi.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://login.microsoftonline.com/common/oauth2/authorize?client_id=871c010f-5e61-4fb1-83ac-98610a7e9110&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dcLbLAGp9KyJKSgdJ2n7kaJjBi-KnFkLjR1QLqfhW_WRScZxvoG0i4G3Ff2PYxSeIoeM_GWUL6ZESDm_KjtdGkzaoLBtIvHMPdt03BX9jSPKEK9FxrWOo7aTeKQL_KtMMaxbiC32G8uNm7UPrTd136A&nonce=637091646961896741.MjNjZTVlOTctMDc3Ni00MTBhLTgxZjYtYmQ1YzExYjFjYWYzYmY0NTgwNzAtMmZmNS00MzczLWFmY2EtNjk0ODQzZGE0NTU0&site_id=500453&redirect_uri=https%3a%2f%2fapp.powerbi.com%2f%3fnoSignUpCheck%3d1&post_logout_redirect_uri=https%3a%2f%2fapp.powerbi.com%2f%3fnoSignUpCheck%3d1&resource=https%3a%2f%2fanalysis.windows.net%2fpowerbi%2fapi&nux=1&msafed=0',
              autoExpand: false,
              position: 10,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c5cb13aa7bd',
              name: 'Oracle Hyperion',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/ksf9m8QY3yB5BCCra/oraclehyperion.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://login.oracle.com/oaam_server/login.do;jsessionid=s8tgFquioCpvap8KJVSxizLnIjLuRR4s6Kwz1Eh8FzXVv771OOyQ!-1378504431!-1789969116',
              autoExpand: false,
              position: 11,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6cb2d23aa7bc',
              name: 'Microsoft Dynamics',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/Rd5yXn7QGTAHA22Lw/microsoftdynamics.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://login.microsoftonline.com/common/oauth2/authorize?client_id=ebf6b2b7-c635-4217-b6b7-21de4ac65764&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3d_7LtczrNf4s7rjab1E0_70r_C5AGEWZG2cYAnXP7EodM-JVCBB9TznFUaFMxkbnoGgg0g8r0JKwo5xe3_sCXZrhbKFupWnf1PVvXOzRDCBKIxXlj252NulvhoyB7LmGa0dh3jvQiFlQiiTonb14_Tw&nonce=637091665807951065.MzAyOTA4OTEtNzhlMS00OGRiLTllYTctNzJmOWJhY2U2YmI4MDg4YjlkZTEtMjVhYi00YThhLTg4N2QtMWU0MGExOTEzN2Iz&redirect_uri=https%3a%2f%2fdynamics.microsoft.com%2f&post_logout_redirect_uri=https%3a%2f%2fdynamics.microsoft.com',
              autoExpand: false,
              position: 12,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c4c273aa7bb',
              name: 'Microsoft Office',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/5o4bgaGBkpMF73SKv/office.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://login.microsoftonline.com/common/oauth2/authorize?client_id=4345a7b9-9a63-4910-a426-35363201d503&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3d0zMv5AgpWPx-_zsU2a3Q97LsomUAQNkoL0seRVLZilMf6C1-za9Ad9Lx4SHaQGbz8kqNX4rNiNAH7yTNq8OjLEgYlEYGGU3L0M12pwzOWYfFZho0M83EHR0CtSuro9Dz&nonce=637091671768077536.Yjk4Y2I4ZjEtOTg5OS00YTY5LWE1N2MtMTUzOWFjZmYwNmRmY2ZiYmFiZGEtMTY4MC00MjdkLWFjZjUtZDRjYzQ0MzliODgx&redirect_uri=https%3a%2f%2fwww.office.com%2f&ui_locales=en-GB&mkt=en-GB&client-request-id=10a5aa58-e4be-403e-acbb-ccfb4e111f38',
              autoExpand: false,
              position: 13,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c61a83aa7ba',
              name: 'Kyriba',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/fbMmPz6Hc9pkkZckk/kyriba.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://www.demo.kyriba.com/user/login',
              autoExpand: false,
              position: 14,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c5e1c3aa7b9',
              name: 'IBM Cognos',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/9g9fgKTsPEEEc74fJ/imb%20cognos.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://www.ibm.com/account/reg/us-en/login?formid=urx-34710',
              autoExpand: false,
              position: 15,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c527f3aa7b8',
              name: 'Oracle EPM',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/f5BgnSAHSAFW4uSLB/oracleepm.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://login.oracle.com/oaam_server/login.do',
              autoExpand: false,
              position: 16,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c46d23aa7b7',
              name: 'Google Spreadsheet',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/wSLEFmNa9T6EYQumT/googlespreadsheet.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://docs.google.com/spreadsheets/u/0/?tgif=d',
              autoExpand: false,
              position: 17,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c3bd43aa7b6',
              name: 'Google Analytics',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/YoYAHb7ge72a5MKob/google%20analytics.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://analytics.google.com/analytics/web/provision/#/provision',
              autoExpand: false,
              position: 18,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c58063aa7b5',
              name: 'Github',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/rwQ8BirXiLhWaXcm7/github.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://github.com/',
              autoExpand: false,
              position: 19,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c33483aa7b4',
              name: 'Excel',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/jkNctAoiZrBkPdGeP/excel.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://products.office.com/en/excel',
              autoExpand: false,
              position: 20,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c634c3aa7b3',
              name: 'FIS',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/LhADLmWm3kFp7d4TP/fis.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://my.fisglobal.com/Login?returnUrl=%2f',
              autoExpand: false,
              position: 21,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6caafc3aa7b2',
              name: 'Diapason',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/E8c5nHvnaFyWbQgYg/diapason.png?token=eyJhdXRoVG9rZW4iOiJ2U1VjZUdXVFNBMzl4X2JPclRlYnlBQ0ZzYVl5SmsyOFFoUk1YbWlSQUR2In0%3D',
              url: 'https://www.diapason-treasury.com/trms/',
              autoExpand: false,
              position: 22,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c4b123aa7b1',
              name: 'Anaplan',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/zPjm25JtxHd6v7YCF/anaplan.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://sdp.anaplan.com/frontdoor/login?service=https%3A%2F%2Fsdp.anaplan.com%2Flaunchpad%2Fnonpublic%2FWorkspaceRedirect.action',
              autoExpand: false,
              position: 23,
            },
            {
              hideElements: [],
              _id: '5dcadafc92b5831195d64310',
              name: 'MicroStrategy',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/5Ze6qd55GL8ghXuGJ/microstrategy.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://celio.cloud.microstrategy.com/MicroStrategy/servlet/mstrWeb',
              autoExpand: false,
              position: 24,
            },
            {
              hideElements: [],
              _id: '5dcadafc92b583f934d6430f',
              name: 'Microsoft Teams',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/C6agvAxida4bZewMC/teams.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://businessstore.microsoft.com/en-us/create-account/signup?products=CFQ7TTC0K8P5:0001',
              autoExpand: false,
              position: 25,
            },
            {
              hideElements: [],
              _id: '5dcadafc92b58367cdd6430e',
              name: 'Toucan Toco',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/J3xwxdJEJprH3ijW8/toucantoco.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://toucantoco.com/en/',
              autoExpand: false,
              position: 26,
            },
            {
              hideElements: [],
              _id: '5dcadafc92b583416cd6430d',
              name: 'PayFit',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/8WvKdBNs5jfbS67mD/payfit.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://app.payfit.com/',
              autoExpand: false,
              position: 27,
            },
            {
              hideElements: [],
              _id: '5dcadafc92b5830362d6430c',
              name: 'Outlook',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/C4oPCw7AmeqwhgfbQ/outlook.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=13&ct=1573574799&rver=7.0.6737.0&wp=MBI_SSL&wreply=https%3a%2f%2foutlook.live.com%2fowa%2f%3fnlp%3d1%26RpsCsrfState%3d67ca894b-4177-10c6-cf98-f3ffeb679ca1&id=292841&aadredir=1&CBCXT=out&lw=1&fl=dob%2cflname%2cwld&cobrandid=90015',
              autoExpand: false,
              position: 28,
            },
            {
              hideElements: [],
              _id: '5dcadafc92b583802dd6430b',
              name: 'Jira',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/AdQFbzB2XToP2faXz/jira.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://id.atlassian.com/login',
              autoExpand: false,
              position: 29,
            },
            {
              hideElements: [],
              _id: '5dcadafc92b5839363d6430a',
              name: 'Confluence',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/ZQDQpPNojyJiF3Gf5/confluence.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://id.atlassian.com/login?atlOrigin=eyJpIjoiYTEwYTdiZDNiNTNlNDUzOWE5OTY1NTQwNzU3Y2Y2ZjMiLCJwIjoid2FjLWxvZ2luIn0&continue=https%3A%2F%2Fwww.atlassian.com%2Fsoftware%2Fconfluence',
              autoExpand: false,
              position: 30,
            },
            {
              hideElements: [],
              _id: '5dcadafc92b583d5f6d64309',
              name: 'Trello',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/3AH68hmRM6XQYM9Xd/trello.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://trello.com/login',
              autoExpand: false,
              position: 31,
            },
            {
              hideElements: [],
              _id: '5dcadc2492b583d349d6449c',
              name: 'Wekan',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/sLm2zJKMMd6dQsxCH/wekan.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://wekan.github.io/demo/login.html',
              autoExpand: false,
              position: 32,
            },
            {
              hideElements: [],
              _id: '5dcae49892b5832abfd64859',
              name: 'Neo',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/ZCYsScDvSvYxcayEs/neo.png?token=eyJhdXRoVG9rZW4iOiJ2U1VjZUdXVFNBMzl4X2JPclRlYnlBQ0ZzYVl5SmsyOFFoUk1YbWlSQUR2In0%3D',
              url: 'https://www.getneo.com/',
              autoExpand: false,
              position: 33,
            },
            {
              hideElements: [],
              _id: '5dcae49892b583c207d64858',
              name: 'Slack',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/57Br5HYja2bgZxff2/slack.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://slack.com/signin',
              autoExpand: false,
              position: 34,
            },
            {
              hideElements: [],
              _id: '5dcae49892b583457cd64857',
              name: 'Google Drive',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/gABMPc5hbntBnZGXP/googledrive.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://drive.google.com/drive/',
              autoExpand: false,
              position: 35,
            },
            {
              hideElements: [],
              _id: '5dcae49892b5833d70d64856',
              name: 'Gmail',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/xMtphHNZxtXDSW8eS/gmail.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://mail.google.com/mail/u/0/#inbox',
              autoExpand: false,
              position: 36,
            },
            {
              hideElements: [],
              _id: '5dcae49892b58397f7d64855',
              name: 'WorkPlace',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/Q46dYNXohpQqEp35L/workplace.png?token=eyJhdXRoVG9rZW4iOiJ2U1VjZUdXVFNBMzl4X2JPclRlYnlBQ0ZzYVl5SmsyOFFoUk1YbWlSQUR2In0%3D',
              url: 'https://work.workplace.com/?session_id=Cq44Oepfabv',
              autoExpand: false,
              position: 37,
            },
            {
              hideElements: [],
              _id: '5dceaece92b5833f82d67093',
              name: 'Board',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/JRa3XBzvZjwNz9idF/board.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://www.board.com/en#gref',
              autoExpand: false,
              position: 38,
            },
            {
              hideElements: [],
              _id: '5dceaece92b5834045d67092',
              name: 'Ubisoft',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/Lqha4bGEhPGQ2upSv/ubisoft.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://account.ubisoft.com/fr-FR/login',
              autoExpand: false,
              position: 39,
            },
            {
              hideElements: [],
              _id: '5dceaece92b583badad67091',
              name: 'Alteryx',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/7SfXiGy5mKsxch4Sp/alteryx.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://gallery.alteryx.com/#!account',
              autoExpand: false,
              position: 40,
            },
            {
              hideElements: [],
              _id: '5dceaece92b5830ab4d67090',
              name: 'Microsoft',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/RpkxfxummT7tMCqk2/microsoft.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://login.microsoftonline.com/common/oauth2/authorize?client_id=871c010f-5e61-4fb1-83ac-98610a7e9110&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dcLbLAGp9KyJKSgdJ2n7kaJjBi-KnFkLjR1QLqfhW_WRScZxvoG0i4G3Ff2PYxSeIoeM_GWUL6ZESDm_KjtdGkzaoLBtIvHMPdt03BX9jSPKEK9FxrWOo7aTeKQL_KtMMaxbiC32G8uNm7UPrTd136A&nonce=637091646961896741.MjNjZTVlOTctMDc3Ni00MTBhLTgxZjYtYmQ1YzExYjFjYWYzYmY0NTgwNzAtMmZmNS00MzczLWFmY2EtNjk0ODQzZGE0NTU0&site_id=500453&redirect_uri=https%3a%2f%2fapp.powerbi.com%2f%3fnoSignUpCheck%3d1&post_logout_redirect_uri=https%3a%2f%2fapp.powerbi.com%2f%3fnoSignUpCheck%3d1&resource=https%3a%2f%2fanalysis.windows.net%2fpowerbi%2fapi&nux=1&msafed=0',
              autoExpand: false,
              position: 41,
            },
            {
              hideElements: [],
              _id: '5dceaf2f92b58388a2d67115',
              name: 'Deltek',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/5r6j2s329FQk86sHn/deltek.png?token=eyJhdXRoVG9rZW4iOiJya1VOekdoeE1sUEpsY1JCNHhyNXl6TTEyZjZTMlNKdndXUTcyOEhrUzRWIn0%3D',
              url: 'https://deltek.custhelp.com/app/utils/login_form/redirect/home?p_ptaid=fUejFs62aliDEWcJ6C0VbVM02WU5DZptlipzimAZxwRfYxaAs9SyN8E_LSVW_Jk%7EkiXd0RNAG87m95INweO4gV5iiqcmHnz77anER0b%7EE6JIK6wuW3hwYXNA%21%21',
              autoExpand: false,
              position: 42,
            },
            {
              hideElements: [],
              _id: '5dd3bdb492b583753ed6a438',
              name: 'Pipedrive',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/WqLxuhML7P3nSxACd/pipedrive.png?token=eyJhdXRoVG9rZW4iOiJ2U1VjZUdXVFNBMzl4X2JPclRlYnlBQ0ZzYVl5SmsyOFFoUk1YbWlSQUR2In0%3D',
              url: 'https://app.pipedrive.com/auth/sso',
              autoExpand: false,
              position: 43,
            },
            {
              hideElements: [],
              _id: '5dd3bdb492b58311afd6a437',
              name: 'Yooz',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/tq73WG55Kj53R7LYW/yooz.png?token=eyJhdXRoVG9rZW4iOiJ2U1VjZUdXVFNBMzl4X2JPclRlYnlBQ0ZzYVl5SmsyOFFoUk1YbWlSQUR2In0%3D',
              url: 'https://www.getyooz.com/customers/',
              autoExpand: false,
              position: 44,
            },
            {
              hideElements: [],
              _id: '5dd3bdb492b583bff5d6a436',
              name: 'Silaexpert',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/HWZ97adBoPe9NgR6a/silaexpert.png?token=eyJhdXRoVG9rZW4iOiJ2U1VjZUdXVFNBMzl4X2JPclRlYnlBQ0ZzYVl5SmsyOFFoUk1YbWlSQUR2In0%3D',
              url: 'https://www.silaexpert.fr/connexion',
              autoExpand: false,
              position: 45,
            },
            {
              hideElements: [],
              _id: '5dd3bdb492b5837c08d6a435',
              name: 'Finex Kap',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/sPBEYso3A6FPK7wiA/finexkap.png?token=eyJhdXRoVG9rZW4iOiJ2U1VjZUdXVFNBMzl4X2JPclRlYnlBQ0ZzYVl5SmsyOFFoUk1YbWlSQUR2In0%3D',
              url: 'https://www.finexkap.com/',
              autoExpand: false,
              position: 46,
            },
            {
              hideElements: [],
              _id: '5dd3bdb492b583a7b2d6a434',
              name: 'Cegid',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/4PZ3wXvtkqQD9oADQ/cegid.png?token=eyJhdXRoVG9rZW4iOiJ2U1VjZUdXVFNBMzl4X2JPclRlYnlBQ0ZzYVl5SmsyOFFoUk1YbWlSQUR2In0%3D',
              url: 'https://www.cegid.com/fr/cegidlife-espace-client-personnalise/',
              autoExpand: false,
              position: 47,
            },
            {
              hideElements: [],
              _id: '5dd3bdb492b5835cbed6a433',
              name: 'Cador',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/zfN9K3wK8qQgkou8B/cador.png?token=eyJhdXRoVG9rZW4iOiJ2U1VjZUdXVFNBMzl4X2JPclRlYnlBQ0ZzYVl5SmsyOFFoUk1YbWlSQUR2In0%3D',
              url: 'https://www.acd-groupe.fr/',
              autoExpand: false,
              position: 48,
            },
          ],
          id: 4,
          title: 'Data factory',
          description: 'Take back control of your data',
        },
        {
          box: [
            {
              hideElements: [],
              _id: '5da87b33502d6c75463aa7b0',
              name: 'Tensorflow',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://www.tensorflow.org/images/graph_vis_animation.gif',
              url: 'https://console.dialogflow.com/api-client/#/login',
              autoExpand: false,
              position: 0,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c0abd3aa7af',
              name: 'Dialogflow',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: false,
              zoom: 100,
              urlBg: 'https://raw.githubusercontent.com/svet4/images/master/img/create-an-intent.gif',
              url: 'https://console.dialogflow.com/api-client/#/login',
              autoExpand: false,
              position: 1,
            },
          ],
          id: 5,
          title: 'AI training',
          description: 'Train Bob, augment your financial data experience',
        },
        {
          box: [
            {
              hideElements: [],
              _id: '5da87b33502d6c42853aa7ae',
              name: 'File Manager',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://css-tricks.com/wp-content/uploads/2015/11/drag-drop-upload-1.gif',
              url: 'ftp.cashstory.com:21',
              autoExpand: true,
              position: 0,
              authMethod: 'filestash_ftp',
              login: {
                username: 'bob@cashstory.com',
                password: 'oTw6H3GY6LI6Ov26er1SETkm',
              },
            },
          ],
          id: 6,
          title: 'File Manager',
          description: 'Drop your files',
        },
        {
          box: [
            {
              hideElements: [],
              _id: '5da87b33502d6cf5f03aa7ad',
              name: 'docker visualisor',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://i.ibb.co/DwsMGBB/Screenshot-2019-06-01-at-03-16-09.png',
              url: 'https://scope.cashstory.com',
              autoExpand: false,
              position: 0,
            },
            {
              hideElements: [],
              _id: '5db70fcabe5ced13810ac770',
              name: 'Workspaces',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              urlBg: 'https://api-mdm-is.toucantoco.com/accountingaudit-firms/assets/bg-1?decache=1564651334504&thumb',
              zoom: 100,
              autoExpand: false,
              position: 1,
              smartTable: {
                database: 'darkknight',
                collection: 'workspaces',
                model: 'workspace',
                rights: [
                  'POST',
                  'GET',
                  'PUT',
                  'DELETE',
                ],
                settings: {
                  actions: {
                    custom: [
                      {
                        name: 'downloadAction',
                        title: '<i class="fal fa-arrow-alt-to-bottom fa-xs p-1 m-1" title="Download"></i>',
                      },
                      {
                        name: 'seeWorkspaceAction',
                        title: '<i class="fal fa-eye fa-xs p-1 m-1" title="See"></i>',
                      },
                      {
                        name: 'editJsonAction',
                        title: '<i class="fal fa-code fa-xs p-1 m-1" title="Edit"></i>',
                      },
                    ],
                    delete: true,
                    add: true,
                    edit: true,
                  },
                  pager: {
                    perPage: 30,
                  },
                  columns: {
                    _id: {
                      title: 'id',
                    },
                    name: {
                      title: 'Name',
                    },
                    updatedAt: {
                      title: 'Last update',
                    },
                  },
                },
              },
            },
            {
              hideElements: [],
              _id: '5db70fcabe5ced32ae0ac76f',
              name: 'Users',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              urlBg: 'https://api-mdm-is.toucantoco.com/accountingaudit-firms/assets/bg-1?decache=1564651334504&thumb',
              zoom: 100,
              autoExpand: false,
              position: 2,
              smartTable: {
                database: 'darkknight',
                collection: 'users',
                model: 'user',
                rights: [
                  'POST',
                  'GET',
                  'PUT',
                  'DELETE',
                ],
                settings: {
                  actions: {
                    custom: [
                      {
                        name: 'downloadAction',
                        title: '<i class="fal fa-arrow-alt-to-bottom fa-xs p-1 m-1" title="Download"></i>',
                      },
                      {
                        name: 'editJsonAction',
                        title: '<i class="fal fa-code fa-xs p-1 m-1" title="Edit"></i>',
                      },
                    ],
                    delete: true,
                    add: true,
                    edit: true,
                  },
                  pager: {
                    perPage: 30,
                  },
                  columns: {
                    firstName: {
                      title: 'Firstname',
                    },
                    lastName: {
                      title: 'Lastname',
                    },
                    email: {
                      title: 'Email',
                    },
                    phoneNumber: {
                      title: 'Phone',
                    },
                    updatedAt: {
                      title: 'Last Loggin',
                    },
                    workspaceCurrent: {
                      title: 'Workspace Current',
                    },
                  },
                },
              },
            },
            {
              hideElements: [],
              _id: '5da87b33502d6ca6903aa7aa',
              name: 'Clockify',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://clockify.me/assets/images/logo.svg',
              url: 'https://clockify.me/tracker',
              autoExpand: false,
              position: 3,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c2b563aa7ac',
              name: 'uptime check',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://i.ibb.co/02JtKHN/Screenshot-2019-06-01-at-03-17-18.png',
              url: 'https://grafana.cashstory.com/d/HUEzXdMZz/galaxy?orgId=1',
              autoExpand: false,
              position: 4,
            },
            {
              hideElements: [],
              _id: '5da87b33502d6c17b13aa7ab',
              name: 'Health machine',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://i.ibb.co/TBJHyqg/Screenshot-2019-06-01-at-03-14-16.png',
              url: 'https://grafana.cashstory.com/d/XGECwOMZk/prometheus-2-0-stats?orgId=1&refresh=1m&kiosk',
              autoExpand: false,
              position: 5,
            },
          ],
          id: 7,
          title: 'CashStory Admin',
          description: 'Transparency and control over our terms',
        },
        {
          box: [
            {
              hideElements: [],
              _id: '5db70fcabe5ced13810ac770',
              name: 'Worspaces',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              urlBg: 'https://api-mdm-is.toucantoco.com/accountingaudit-firms/assets/bg-1?decache=1564651334504&thumb',
              zoom: 100,
              autoExpand: true,
              position: 0,
              smartTable: {
                database: 'darkknight',
                collection: 'workspaces',
                model: 'workspace',
                rights: [
                  'POST',
                  'GET',
                  'PUT',
                  'DELETE',
                ],
                settings: {
                  actions: {
                    custom: [
                      {
                        name: 'downloadAction',
                        title: '<i class="fal fa-arrow-alt-to-bottom fa-xs p-1 m-1" title="Download"></i>',
                      },
                      {
                        name: 'seeWorkspaceAction',
                        title: '<i class="fal fa-eye fa-xs p-1 m-1" title="See"></i>',
                      },
                      {
                        name: 'editJsonAction',
                        title: '<i class="fal fa-code fa-xs p-1 m-1" title="Edit"></i>',
                      },
                    ],
                    delete: true,
                    add: true,
                    edit: true,
                  },
                  pager: {
                    perPage: 30,
                  },
                  columns: {
                    _id: {
                      title: 'id',
                    },
                    name: {
                      title: 'Name',
                    },
                    updatedAt: {
                      title: 'Last update',
                    },
                  },
                },
              },
            },
          ],
          id: 8,
          title: 'CashStory Admin',
          description: 'Transparency and control over our terms',
        },
        {
          box: [
            {
              hideElements: [],
              _id: '5db70fcabe5ced32ae0ac76f',
              name: 'Users',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              urlBg: 'https://api-mdm-is.toucantoco.com/accountingaudit-firms/assets/bg-1?decache=1564651334504&thumb',
              zoom: 100,
              autoExpand: true,
              position: 0,
              smartTable: {
                database: 'darkknight',
                collection: 'users',
                model: 'user',
                rights: [
                  'POST',
                  'GET',
                  'PUT',
                  'DELETE',
                ],
                settings: {
                  actions: {
                    custom: [
                      {
                        name: 'downloadAction',
                        title: '<i class="fal fa-arrow-alt-to-bottom fa-xs p-1 m-1" title="Download"></i>',
                      },
                      {
                        name: 'editJsonAction',
                        title: '<i class="fal fa-code fa-xs p-1 m-1" title="Edit"></i>',
                      },
                    ],
                    delete: true,
                    add: true,
                    edit: true,
                  },
                  pager: {
                    perPage: 30,
                  },
                  columns: {
                    firstName: {
                      title: 'Firstname',
                    },
                    lastName: {
                      title: 'Lastname',
                    },
                    email: {
                      title: 'Email',
                    },
                    phoneNumber: {
                      title: 'Phone',
                    },
                    updatedAt: {
                      title: 'Last Loggin',
                    },
                    workspaceCurrent: {
                      title: 'Workspace Current',
                    },
                  },
                },
              },
            },
          ],
          id: 9,
          title: 'CashStory Admin',
          description: 'Transparency and control over our terms',
        },
      ],
    });
    await initWorkspace({
      _id: '5eaa9b7c87e99ef2430a270a',
      logo: {
        url: '.../../../assets/logo/nexity.png',
        name: 'testUpload',
      },
      name: 'My Workspace',
      bobVoice: false,
      menu: [
        {
          title: 'Toucan Toco',
          icon: 'tablet',
          sectionId: 1,
        },
        {
          title: 'Task Manager',
          icon: 'tasks',
          sectionId: 2,
        },
      ],
      sections: [
        {
          box: [
            {
              hideElements: [],
              _id: '5da87a01502d6c170b3aa64d',
              name: 'Toucan Toco',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://api.toucan.cashstory.com/cashstory-demo/assets/bg-1?decache=1568240830525',
              url: 'https://viz.cashstory.com/cashstory-demo?report=0&dashboard=0',
              autoExpand: true,
              position: 0,
              authMethod: 'toucan',
              login: {
                username: 'demo@cashstory.com',
                password: 'welcomebob',
              },
            },
          ],
          id: 1,
          title: 'Stories',
          description: 'Follow your financial & extra-financial performance',
        },
        {
          box: [
            {
              hideElements: [],
              _id: '5da87a01502d6c7cbb3aa64c',
              name: 'Task Manager',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/Jbn7qSXR5GEiJv3yL/undraw_schedule_pnbk.png?token=eyJhdXRoVG9rZW4iOiItU2poWTQwY1p4WFVHejlSRHZsLTFzdENfMkx1b205U2dDS2Jac0ptb3JWIn0%3D',
              url: 'https://task.cashstory.com/b/SomaKgDQSSR2z92hd/app-treasurers',
              autoExpand: true,
              position: 0,
            },
          ],
          id: 2,
          title: 'Agility Manager',
          description: 'Manage AI tasks, with our augmented to-do list',
        },
        {
          box: [
            {
              hideElements: [],
              _id: '5da87a01502d6c33813aa64b',
              name: 'Documentation',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://images.pexels.com/photos/1485114/pexels-photo-1485114.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
              url: 'https://docs.google.com/document/d/1U8CDv5O1xORf2QWYtDOKb8i1WJ3reXeM2SlkG1b6iis/edit',
              autoExpand: false,
              position: 0,
            },
            {
              hideElements: [],
              _id: '5da87a01502d6c6e873aa64a',
              name: 'File Manager Upload File Drive',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/BG42rQNLWya96sTtf/undraw_uploading_go67.png?token=eyJhdXRoVG9rZW4iOiItU2poWTQwY1p4WFVHejlSRHZsLTFzdENfMkx1b205U2dDS2Jac0ptb3JWIn0%3D',
              url: 'https://files.cashstory.com',
              autoExpand: true,
              position: 1,
            },
          ],
          id: 5,
          title: 'AI training',
          description: 'Transparency and control over our terms',
        },
        {
          box: [
            {
              hideElements: [],
              _id: '5da87a01502d6ca15f3aa649',
              name: 'Spreadsheet',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: 'https://task.cashstory.com/cfs/files/attachments/B33Rv77zdQ4SKSCgo/undraw_spreadsheets_xdjy.png?token=eyJhdXRoVG9rZW4iOiItU2poWTQwY1p4WFVHejlSRHZsLTFzdENfMkx1b205U2dDS2Jac0ptb3JWIn0%3D',
              url: 'https://docs.google.com/spreadsheets/d/1_8xPyfKtdWJzEJchUw1tRCTwDLFGgiO7bKS0Ql452vU/edit#gid=0',
              autoExpand: true,
              position: 0,
            },
          ],
          id: 6,
          title: 'Spreadsheet',
          description: 'Transparency and control over our terms',
        },
        {
          box: [
            {
              hideElements: [],
              _id: '5da87a01502d6ca15f3aa649',
              name: 'Cashflow',
              color: '#ffffff',
              backgroundColor: '#a0a0a0',
              iframe: true,
              zoom: 100,
              urlBg: '',
              url: 'https://viz.cashstory.com/cashstory-demo?view=My%20Company&report=My%2520Company&slide=202&dashboard=0&filters=%257B%257D&requesters=%257B%2522APP_REPORT_REQUESTER_ID%2522%3A%2522My%2520Company%2522%2C%2522APP_DATE_REQUESTER_ID%2522%3A%2522Dec%25202019%2522%2C%2522UPPER_FILTER_M_221%2522%3A%2522All%2520Banks%2522%2C%2522UPPER_FILTER_R_221%2522%3A%2522All%2520Accounts%2522%257D&crossfilter=%257B%257D',
              autoExpand: true,
              position: 0,
            },
          ],
          id: 7,
          title: 'Cashflow',
          description: 'Transparency and control over our terms',
        },
      ],
    });
    await initUser({
      email: 'test@cashstory.com',
      role: 'user',
      tmpAccount: false,
      password: 'testworkspace',
      firstName: 'test ',
      lastName: 'Cashstory',
      workspaces: {
        '5eaa9b7c87e99ef2430a270a': {
          news: { sources: [], categories: [], name: 'News' },
          favorites: {
            boxes: [],
            class: 'col-12 col-md-6 px-0 px-md-3',
            name: 'Favoris',
          },
          name: 'My Workspace',
        },
      },
    });
    await initUser({
      email: 'bob@cashstory.com',
      role: 'admin',
      tmpAccount: false,
      password: 'bobworkspace',
      firstName: 'Bob ',
      lastName: 'Cashstory',
      workspaces: {
        '5eaa9b7c87e99ef2430a270a': {
          news: { sources: [], categories: [], name: 'News' },
          favorites: {
            boxes: [],
            class: 'col-12 col-md-6 px-0 px-md-3',
            name: 'Favoris',
          },
          name: 'My Workspace',
        },
        '5cc22e6efc3b6947d92d37f2': {
          news: {
            sources: [], categories: [], name: 'News', lang: 'en',
          },
          favorites: {
            boxes: [], name: 'Favoris',
          },
          name: 'admin',
        },
      },
    });
  }
};
